package net.alek.succorstadiums.item.equipment.pouch;

import net.minecraft.world.SimpleContainer;
import net.minecraft.world.item.ItemStack;
import net.minecraft.core.NonNullList;

import java.util.function.Consumer;

// PouchContainer class
public class PouchContainer extends SimpleContainer {
    private final Consumer<PouchContents> onChanged;

    public PouchContainer(PouchContents contents, Consumer<PouchContents> onChanged) {
        super(contents.copyItems().toArray(new ItemStack[0]));
        this.onChanged = onChanged;
    }

    // Override the getMaxStackSize method with our custom max stack size
    @Override
    public int getMaxStackSize() {
        return PouchContents.MAX_STACK_SIZE;
    }

    // Override the setChanged method and write back what item changes happened to pouch contents from a list generated by snapshot
    @Override
    public void setChanged() {
        super.setChanged();
        this.onChanged.accept(this.snapshot());
    }

    // Create a list of each itemstack in the pouch content
    private PouchContents snapshot() {
        NonNullList<ItemStack> list = NonNullList.withSize(PouchContents.SLOT_COUNT, ItemStack.EMPTY);

        // Iterate through the container slots and write into the list
        for (int i = 0; i < this.getContainerSize(); i++) {
            list.set(i, this.getItem(i).copy());
        }

        // Return the new list of pouch contents to the set changed method
        return PouchContents.of(list);
    }
}